apiVersion: batch/v1
kind: Job
metadata:
  name: airflow-db-init
  namespace: airflow
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: airflow-init
          image: apache/airflow:3.0.2
          command: ["bash", "-c"]
          args:
            - airflow db migrate
          envFrom:
            - secretRef:
                name: airflow-secrets
