apiVersion: v1
kind: Secret

metadata:
  name: airflow-secrets
  namespace: airflow
type: Opaque
stringData:
  AIRFLOW__CORE__FERNET_KEY: "T4n2q3dZlL4mQ8Xr0y7C5bR2fKp9gS1uVx8aC4p6g0E"
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
