apiVersion: batch/v1
kind: Job
metadata:
  name: airflow-create-user
  namespace: airflow
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: create-user
          image: apache/airflow:3.0.2
          command: ["bash", "-c"]
          args:
            - |
              airflow users create \
                --username admin \
                --password admin \
                --firstname Admin \
                --lastname User \
                --role Admin \
                --email admin@example.com
          envFrom:
            - secretRef:
                name: airflow-secrets
