executor: "KubernetesExecutor"
# executor: "LocalExecutor"

fernetKey: "T4n2q3dZlL4mQ8Xr0y7C5bR2fKp9gS1uVx8aC4p6g0E="
webserverSecretKey: "p9NwQ3xLz6RkT1aYb4UeG8cVh2PmW7sKd0FjS3rQv8ZtX5wBq1CnH9Ly0DsE4R"

# Images
images:
  airflow:
    repository: my-dags
    tag: "0.0.1"
    # Specifying digest takes precedence over tag.
    digest: ~
    pullPolicy: IfNotPresent

dags:
  gitSync:
    enabled: true

    # git repo clone url
    # ssh example: git@github.com:apache/airflow.git
    # https example: https://github.com/apache/airflow.git
    repo: https://github.com/Chanura04/ai-stack-exchange-analyser.git
    branch: main
    rev: HEAD
    # The git revision (branch, tag, or hash) to check out, v4 only
    ref: main
    depth: 1
    # the number of consecutive failures allowed before aborting
    maxFailures: 0
    # subpath within the repo where dags are located
    # should be "" if dags are at repo root
    subPath: "dags"
    credentialsSecret: git-credentials


postgresql:
  enabled: true
  image:
    repository: postgres
    tag: "15"
    pullPolicy: IfNotPresent
  auth:
    username: postgres
    password: postgres
    database: airflow

