apiVersion: v1
kind: Secret
metadata:
  name: git-credentials
  namespace: airflow
stringData:
  GITSYNC_USERNAME: Chanura04
  GITSYNC_PASSWORD: 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
  GIT_SYNC_USERNAME: Chanura04
  GIT_SYNC_PASSWORD: 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
